### ISSUE TITLE
Use Adapter and WiFi dongle at the same time

### ISSUE THREAD

**Issue by SandroMueller** [ByteSeekerPro/PowMr-POW-SunSmart-12KL3-RS485-HomeAssistant-Integration#1]
Hi! Is there a way to use the WiFi Dongle and the RS485 to TTL converter at the same time? Why not use the second RS485 port on the POW-SunSmart 12KL3? I would not like to lose the manufacturer's app functionality. Thanks for your help!

**Comment by ByteSeekerPro** [comment]
Hi,
I have only had a similar inverter from Powmr so far. With that one, simultaneous use was not possible. I did not buy the WiFi adapter for this one; I manage the inverter via Home Assistant. For this reason, I unfortunately cannot test whether simultaneous use is possible with this device.
However, I could use a second ESP and check if both work :-). I will test this and post the result here.
Best regards

**Comment by ByteSeekerPro** [comment]
Both adapters work simultaneously, so it will probably also work with the combination of WiFi adapter and ESP.
Best regards

**Comment by SandroMueller** [comment]
> Both adapters work simultaneously, so it will probably also work with the combination of WiFi adapter and ESP. Best regards

Thank you for testing & reporting. I will try it.
Best regards
