### ISSUE TITLE
Tested working: POW-HPM5.6KW

### ISSUE THREAD

**Issue by Smoria** [ByteSeekerPro/PowMr-POW-SunSmart-12KL3-RS485-HomeAssistant-Integration#2]
**Not an issue, just a note that POW-HPM5.6KW works perfectly.**

Only all registers for **PV2 and L2, L3** must be removed or inverter will return errors that those registers are non existent

**Comment by attika1981** [comment]
Confirming, HPM5.6 works perfect, huge thanks for this!

**Comment by ByteSeekerPro** [comment]
Thank you very much for this information. I will update the page and include it.
